server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/appdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  spring:
  security:
    debug: true

logging:
  level:
    org.springframework.security: DEBUG

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+CHARS"
    expirationMs: 3600000
  cors:
    allowed-origins: "http://localhost:4200,http://127.0.0.1:4200,http://localhost:8080,http://127.0.0.1:8080"


management:
  endpoints:
    web:
      exposure:
        include: health,info


